kind: Service
apiVersion: v1
metadata:
  name: spring-helloworld
spec:
  type: LoadBalancer
  selector:
    app: spring-helloworld
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web
