apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld
        image: cloudmonster123/spring-boot-app-k8s_deployment-new:v97
        ports:
        - name: web
          containerPort: 8888
